### ISSUE TITLE
what now?

### ISSUE THREAD

**Issue by ixenion** [darkestentropy/bombcrack#2]
You did a great work.
But if bomber.py really contains APIs and other important information you should understand there is possibility that Tbomb will stop working soon. It could be damaged, broken or somesing else by someone just with your code. You should just tell us whether bomber.py safe or not and delete your repo. You don't want Tbomb to be broken, do you? Otherwise we all lose Tbomb.

**Comment by darkestentropy** [comment]
@EVRICA, I have to close this issue as it's [not related to this project in any way](https://github.com/darkestentropy/bombcrack/issues/1#issuecomment-525228227).
