### ISSUE TITLE
TakeDown Request

### ISSUE THREAD

**Issue by TheSpeedX** [darkestentropy/bombcrack#3]
@darkestentropy I have Changed The License Of TBomb 

So regarding it I am requesting you to Take bombcrack down 

Hope that You will understand and not take it in a negative way

I was not actually bothered about this making you to take down till I got heavy request on my server and overloading it which was due to exposed API which might be the effect of this repo 

So i kindly request you to take it down...

**Comment by darkestentropy** [comment]
Negative, @TheSpeedX.
See response of [#1](https://github.com/darkestentropy/bombcrack/issues/1#issuecomment-543710106).
