### ISSUE TITLE
TBomb new obfuscation compatibility patch

### ISSUE THREAD

**Issue by ghost** [darkestentropy/bombcrack#4]
TBomb's using new obfuscation lately. Here's a quick patch to make bombcrack work just as perfect.

The obfuscation is all the same, but `zlib` and `lzma` compressions are swapped.

## Modifications
*What does this patch do?*
* Pull TBomb files right from ~~TheSpeedX/TBomb~~ darkestentropy/TBomb@historical since historical update of BombCrack
* Crack latest TBomb script

## Download
*.patch file is updated in-place, these links will always provide you with the newest version*
Google Drive ([direct download](http://bit.ly/33GoQKv)/[alternative](http://bit.ly/2IKpper))

## Installation (requires Git)
* Download `newcompat.patch` file to the bombcrack location (put it next to Makefile)
* Rollback previously applied patch with `git apply -R <patch file>` (skip this step if you didn't apply any patches to the repo before - patches usually conflict)
* Run `git apply newcompat.patch`
* Use bombcrack as usual

**Note**: do not delete .patch file after applying it so you can rollback its changes later.

**Comment by darkestentropy** [comment]
**Confirmed** - bombcrack indeed does not work on newer versions of TBomb, and this patch of yours resolves this issue.
However, this workaround won't be added to README, but rather pinned in *Issues*.

Thanks!

**Comment by ghost** [comment]
Thanks for pinning this, @darkestentropy!
Will keep TBomb on track and once they mess up their code some other way - I'll be sure to find a workaround!

**Comment by ghost** [comment]
## Patch Update
Patch updated for the changes made in crack scripts.

## Known issues
~~`git apply` may print out a warning about tab indentation. It's not critical, just ignore it.
Waiting for @darkestentropy to fix indentation in Make.bat/Makefile~~
Seems to be resolved by commit 6c2cb1118e49e506a4e1592e14454869454bf03f.

[Downloads/installation instructions](https://github.com/darkestentropy/bombcrack/issues/4#issue-506305102)

**Comment by darkestentropy** [comment]
@scpketer, patching no longer works.

**Comment by ghost** [comment]
Yep, @darkestentropy, problem spotted right after tabbing update. Working on a fix.

**Comment by ghost** [comment]
## Patch Update
Patch applying problem resolved.

[Downloads/installation instructions](https://github.com/darkestentropy/bombcrack/issues/4#issue-506305102)

**Comment by darkestentropy** [comment]
You're now in charge here, @scpketer.

*assigns scpketer to this issue/thread*

**Comment by darkestentropy** [comment]
Hey, @scpketer!

Due to [publishing source code of TBomb](https://github.com/TheSpeedX/TBomb/issues/41), BombCrack project is being frozen for an indeterminate time. Thanks for your contribution! I'll be sure to notify you once BombCrack is back on.

**Comment by darkestentropy** [comment]
Hey, @scpketer! A historical update was released, and your compatibility patch should be updated.

Historical update commit: c2f6075ff8ed9754e54afbcb369d5c5ad3d58e1e

*Thread is unlocked until patch update is released*

**Comment by ghost** [comment]
Sure, @darkestentropy! Rolled it out!

## Patch Update
Historical update compatibility fixes.

[Downloads/installation instructions](https://github.com/darkestentropy/bombcrack/issues/4#issue-506305102)

**Comment by darkestentropy** [comment]
This patch has been merged in in #8.

**Comment by ghost** [comment]
Yeah, thanks a lot for applying it. I'd make it a PR back then, though it's better not to, though.
