### ISSUE TITLE
Best Repo EVER!

### ISSUE THREAD

**Issue by KnightSec-Official** [darkestentropy/bombcrack#5]
I am a 'medium' hacker, programmer and OSINT 'hacker'! i was trying hardly to decompress everything to see how the tool was made, speedx knew if the tool was going to be open source, the sms bombing will stop cuz the server overload and security measurings... this repo, made my absolutely MONTH! xD You have my respect!

**Comment by darkestentropy** [comment]
I appreciate your support, it really means a lot to me. I have to thank *you*~
