### ISSUE TITLE
Tool not working on the new Tbomb without minor manual modifications

### ISSUE THREAD

**Issue by KnightSec-Official** [darkestentropy/bombcrack#6]
The tool doesnt work on the new tbomb... i modified the make file and made it thespeedx/tbomb.git but gives this error ``` Traceback (most recent call last):
  File "/var/root/Desktop/Desktop/HAX/bombcrack/Crack/decompress_zlib.py", line 37, in <module>
    decompressed = zlib.decompress(decoded)
zlib.error: Error -3 while decompressing data: incorrect header check
make: *** [crack] Error 1 ```

EDIT: ACTUALLY it doesnt need to be on a new version of Tbomb.. the one from your fork worked well.... well, i had to remove the code verification, the protection list and other shit from there... the decompressed tool works AMAZING now.. i will make a repo on a different open source website and put it there.... imma modify it so thespeedx can shut the fuck up xD... THank You SO Much!! Whoever wants to get the Tbomb pre-cracked needs this repo.. well.. if a skid wants it... i will send the modified version without code verification and shit to you.. contact me on discord Knightsec#1316

**Comment by darkestentropy** [comment]
BombCrack is in barest maintenance state right now due to TBomb license changes that affect conditions of modifying source code.

Actually, @scpketer has made a patch that resolves this problem: #4

**Comment by ghost** [comment]
Hey, @KnightSec-Official!

Looks like we follow the same paths :D

How about teaming up?
Contact me via [Telegram](https://t.me/scpketer_510) or [E-mail](mailto:scpketer3@gmail.com) (scpketer3@gmail.com).

I've got ready-to-use bomber based off the sources with all checks and stuff cut off.

**Comment by darkestentropy** [comment]
Since #8 bombcrack is able to deobfuscate newer TBomb versions.
