### ISSUE TITLE
TBomb is no longer obfuscated

### ISSUE THREAD

**Issue by TheSpeedX** [darkestentropy/bombcrack#7]
TBomb is No Longer Obfuscated xD
Thanks To You @darkestentropy and @scpketer For Your Help

Looking Forward To Your Contributions !!!

The Code Might Be A bit naive Cause i coded it long ago xD

**Comment by darkestentropy** [comment]
Great news! If so, bombcrack will be really abandoned from now on.
Will get in touch with you at TBomb repo :)
